flags:
  aeson:
    mintime15: false
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- time-1.5.0.1
- BoundedChan-1.0.3.0
- SHA-1.6.4.2
- aeson-0.8.1.1
- attoparsec-0.13.0.1
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.1
- bytestring-lexing-0.5.0.2
- case-insensitive-1.2.0.4
- cereal-0.4.1.1
- crypto-api-0.13.2
- dlist-0.7.1.1
- entropy-0.3.7
- hashable-1.2.3.3
- hedis-0.6.8
- monad-control-1.0.0.4
- mtl-2.2.1
- network-2.6.2.1
- parsec-3.1.9
- pureMD5-2.1.2.1
- pyfi-0.4.0.4
- regex-base-0.93.2
- regex-posix-0.95.2
- resource-pool-0.2.3.2
- scientific-0.3.3.8
- strict-0.3.2
- tagged-0.8.1
- text-1.2.1.1
- transformers-0.4.3.0
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- websockets-0.9.5.0
- directory-1.2.2.1
- process-1.2.3.0
- random-1.1
- unix-2.7.1.0

- daemons-0.2.1
- data-default-0.5.3
- pipes-4.1.5
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- mmorph-1.0.4

- monad-loops-0.4.3




resolver: ghc-7.8
