flags: {}

packages:
- '.'
extra-deps:
- bytestring-show-0.3.5.6
- daemons-0.2.1
- inline-r-0.7.3.0
- ekg-0.4.0.9
- ekg-json-0.1.0.1
- located-base-0.1.0.0

resolver: lts-3.7

docker:
  enable: false
  repo: alphasheets/backend:latest
