import React from 'react';
import Constants from '../Constants';
import Store from '../stores/ASEvaluationStore';
import Util from '../AS/Util';
let TextareaAutosize = require('react-autosize-textarea');

/*
TODO: REFACTOR
This component uses pixels to calculate the positioning from the top left of spreadsheet. 
I don't see a way with percents right now
Multiline generated by pressing enter within the input tag also doesn't work
Can't find a good expanding component that works
I don't think these are too pressing right now
--Ritesh 10/12 */


export default React.createClass({

  getInitialState(){
    return {
      textBox:null
    };
  },

  updateTextBox(xp,isTyping){
    let col = Store.getActiveSelection().range.col,
        row = Store.getActiveSelection().range.row,
        textBox = {col: col, row: row, xp:xp};
    if (isTyping){
      this.setState({textBox:textBox});
    }
    else{
      this.setState({textBox:null});
    }
  },

  textBoxChange(e){
    this.props.textBoxChange(e.target.value);
  },

  getWidth(xp){
    let rows = xp.split("\n"),
        longestStr = rows.reduce(function (a, b) { return a.length > b.length ? a : b; });
    return Math.max(50,30+(longestStr.length)*12);
  },

  render() {
    let baseStyle = {display:'block',
                     position:'absolute',
                     width:"100%",
                     top: this.state.textBox ? 
                      (this.state.textBox.row-1) * Constants.cellHeightPx + Constants.gridYOffset: 0,
                     left: this.state.textBox ? 
                      (this.state.textBox.col-1) * Constants.cellWidthPx + Constants.gridXOffset: 0,
                     zIndex:5
                     };
    let textStyle = {
      width: this.state.textBox ? this.getWidth(this.state.textBox.xp) : 0,
      border: "solid 3px black"
    };

    /* TODO: using autofocus has the bug that the cursor is at the beginning of the box
    at the start */
    let overlay = this.state.textBox ? 
          <TextareaAutosize ref="box" type="text" autoFocus onFocus={this.onFocus}
                 style={textStyle}
                 onKeyDown={this.props.onKeyDown}
                 value={this.state.textBox.xp} 
                 onChange={this.textBoxChange}/> : null ;
    
    return (
        <div style={baseStyle} >
          {overlay}
         
        </div>
    );
  }

});
